# Generated by Django 6.0.7 on 2026-07-20 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='drop_date',
            new_name='dropoff_date',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='pick_date',
            new_name='pickup_date',
        ),
    ]
