# Generated by Django 6.0.7 on 2026-07-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='total_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
