# Generated by Django 6.0.7 on 2026-07-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='fleet_status',
            field=models.CharField(choices=[('Available', 'Available'), ('Maintenance', 'Maintenance'), ('Inactive', 'Inactive')], default='Available', max_length=20),
        ),
        migrations.AddField(
            model_name='car',
            name='maintenance_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='maintenance_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='car',
            name='plate_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
