# Generated by Django 6.0.7 on 2026-07-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_car_fleet_status_car_maintenance_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='document_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='driver_license',
            field=models.FileField(blank=True, null=True, upload_to='documents/licenses/'),
        ),
        migrations.AddField(
            model_name='booking',
            name='national_id',
            field=models.FileField(blank=True, null=True, upload_to='documents/ids/'),
        ),
    ]
