# Generated by Django 6.0.7 on 2026-07-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_booking_document_status_booking_driver_license_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pickup_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
