# Generated by Django 6.0.7 on 2026-07-30 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_booking_pickup_completed_booking_return_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='available',
        ),
    ]
