# Generated by Django 6.0.7 on 2026-08-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fleet_status',
            field=models.CharField(choices=[('Available', 'Available'), ('Rented', 'Rented'), ('Maintenance', 'Maintenance'), ('Inactive', 'Inactive')], default='Available', max_length=20),
        ),
    ]
