# Generated by Django 6.0.7 on 2026-08-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_booking_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
