# Generated by Django 6.0.7 on 2026-08-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_booking_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Chapa', 'Chapa'), ('Telebirr', 'Telebirr'), ('Cash', 'Cash')], max_length=50, null=True),
        ),
    ]
