# Generated by Django 6.0.7 on 2026-08-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_booking_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='air_conditioning',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='car',
            name='doors',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='car',
            name='features',
            field=models.TextField(blank=True, help_text='Example: Bluetooth, USB, Rear Camera, Cruise Control'),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Hybrid', 'Hybrid'), ('Electric', 'Electric')], default='Petrol', max_length=30),
        ),
        migrations.AddField(
            model_name='car',
            name='luggage_capacity',
            field=models.CharField(blank=True, help_text='Example: 2 large bags', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='seats',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], default='Automatic', max_length=30),
        ),
    ]
