# Generated by Django 6.0.7 on 2026-08-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_car_air_conditioning_car_doors_car_features_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='luggage_capacity',
            field=models.CharField(blank=True, choices=[('1 small bag', '1 small bag'), ('2 small bags', '2 small bags'), ('1 large bag', '1 large bag'), ('2 large bags', '2 large bags'), ('3 large bags', '3 large bags'), ('4 large bags', '4 large bags'), ('5+ large bags', '5+ large bags')], help_text="Select the vehicle's luggage capacity.", max_length=50),
        ),
    ]
