# Generated by Django 6.0.7 on 2026-08-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_car_luggage_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pickup_fuel_level',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_mileage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='fleet_status',
            field=models.CharField(choices=[('Available', 'Available'), ('Maintenance', 'Maintenance'), ('Inactive', 'Inactive')], default='Available', max_length=20),
        ),
    ]
